### ISSUE TITLE
numbers very hard ro see in dark mode

### ISSUE THREAD

**Issue by splace** [alexkdeveloper/sudoku#2]
![image](https://user-images.githubusercontent.com/1234848/205516539-14ba7a5f-e12a-4574-b6bf-8d4c7e033c54.png)

**Comment by alexkdeveloper** [comment]
The application is based on an old program written for elementary os. No special changes were made to the code for rendering the grid of the playing field. Apparently, the developer did not take into account the dark theme. 
It will probably be possible to solve this problem in future versions of the program.
