### ISSUE TITLE
qqwing is not listed as a dependency

### ISSUE THREAD

**Issue by begin-theadventure** [alexkdeveloper/sudoku#3]
https://github.com/alexkdeveloper/sudoku/blob/main/meson.build#L51

**Comment by alexkdeveloper** [comment]
If I register qqwing as a dependency in the meson.build file, then the flatpak package will not be built for me. 

The IDE writes that this package was not found.

Some vapi files will probably be needed here. 
Do you have any ideas about this?

**Comment by begin-theadventure** [comment]
I also got an error after adding it: `error: Package 'qqwing' not found in specified Vala API directories or GObject-Introspection GIR directories`.

This seems to be a problem with the Vala language. The "qqwing" dependency is not on the list (ls /usr/share/vala-0.56/vapi), which causes a compilation error.

**Comment by alexkdeveloper** [comment]
The basis for this application is the long-abandoned [Sudokular](https://github.com/unbelievableflavour/sudokular) application.  
There is also no qqwing in the build script. But it is mentioned in the control file in the debian folder.

**Comment by alexkdeveloper** [comment]
The qqwing package is available in the repositories of many distributions.
